### ISSUE TITLE
Factorio 0.16

### ISSUE THREAD

**Issue by Lafreakshow** [Cerbrus/FactorioMods-TogglePeacefulMode#1]
Mind bumping up the mod to Factorio 0.16?

**Comment by Cerbrus** [comment]
I'll have a look at it. I haven't loaded up factorio in a while...

**Comment by Cerbrus** [comment]
Should be updated now, @Lafreakshow :-)

**Comment by Lafreakshow** [comment]
Well that was quick. You have my Thanks.
