### ISSUE TITLE
Factorio 2.0/Space Age

### ISSUE THREAD

**Issue by ancorehraq** [Cerbrus/FactorioMods-TogglePeacefulMode#10]
Any chance we could get an update for the expansion? The mod would probably need special handling for Gleba enemies and Vulcanus worms.

**Comment by Cerbrus** [comment]
I've not played Factorio in quite some time. Looking back at the code, it -might- work with the new planets / enemies, if they use the same `biter_faction_` in the name.

I don't know when I'll have time to look into this, though.

**Comment by Cerbrus** [comment]
Another user tested the mod locally in 2.0, and it still works for the main world (#11). I've published a release to enable the mod with version 2.0 of the game, under the disclaimer that it's untested in the Space Age worlds.

**Comment by bqv** [comment]
Can it toggle the "No Enemies" mode too? On space age, pentapod eggs will hatch into enemies. That's specifically what I want to disable
