### ISSUE TITLE
updating to 1.0?

### ISSUE THREAD

**Issue by nicrieser** [Cerbrus/FactorioMods-TogglePeacefulMode#4]
Is there any possibility you will ever update this mod to the newest version?

**Comment by Cerbrus** [comment]
I'll have a shot at it, @nicrieser. It's been ages since I've looked at this code, let alone modified it.

**Comment by Cerbrus** [comment]
Well that wasn't too difficult. I've updated the mod in the mod portal:
https://mods.factorio.com/mod/TogglePeacefulMode

**Comment by nicrieser** [comment]
woah, that was really fast, thank you soo much :)

**Comment by Cerbrus** [comment]
No problem @nicrieser! Let me know if you run into any issues.
