### ISSUE TITLE
v0.3 - Error when adding to an existing save

### ISSUE THREAD

**Issue by ssanderlin** [Cerbrus/FactorioMods-TogglePeacefulMode#7]
Adding v0.3 to an existing save results in the following error. Does not occur with a brand new game. No previous version of this mod was installed.

> Error while applying migration: Toggle Peaceful Mode: TogglePeacefulMode_0.3.0.lua
> 
> Gui element with name tpm-button already present in the parent element.
> stack traceback:
> 	[C]: in function 'add'
> 	__TogglePeacefulMode__/tpm/gui/layout.lua:7: in function 'init'
> 	...lePeacefulMode__/migrations/TogglePeacefulMode_0.3.0.lua:12: in main chunk

**Comment by Cerbrus** [comment]
Fixed and verified in 0.3.1
